name: .NET Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v4

    - name: .NET 7 installieren
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Restore
      run: dotnet restore Implementierung/SchulbibliothekWpf/SchulbibliothekWpf.sln

    - name: Build
      run: dotnet build Implementierung/SchulbibliothekWpf/SchulbibliothekWpf.sln --no-restore

    - name: Test
      run: dotnet test Implementierung/SchulbibliothekWpf/SchulbibliothekWpf.sln --no-build --verbosity normal
