name: .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore Implementierung/SchulbibliothekWpf.sln

      - name: Build
        run: dotnet build --no-restore Implementierung/SchulbibliothekWpf.sln

      - name: Test
        run: dotnet test --no-build Implementierung/SchulbibliothekWpf.sln
